# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc262c34de7da747b67f1e068010b5ea00a8b3f8442359254d647a2095b0e1da37d466c4edf6829aa67f7bcf03569c7fc139069ec01d6c13c7e14d8d76e391fc

test:
  secret_key_base: b9672a8ac40b474fce7832650c626c28d660a7a135b1ba0f4bcdb42062bd55d495e4c676cd8f57109add75405de2e88546a0d3eacbc5aced0b413ecafc6c5231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
